# Criado por: Cleber Cisne Cat√£o
# Projeto: Desafio Java
# Data: 19/11/2025

version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amanha
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - desafio-net

  app1:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/desafio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: amanha
      SERVER_PORT: 8081
    depends_on:
      - postgres
    networks:
      - desafio-net

  app2:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/desafio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: amanha
      SERVER_PORT: 8082
    depends_on:
      - postgres
    networks:
      - desafio-net

  app3:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/desafio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: amanha
      SERVER_PORT: 8083
    depends_on:
      - postgres
    networks:
      - desafio-net

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - desafio-net

volumes:
  pgdata:

networks:
  desafio-net:
    driver: bridge
