#  Criado por: Cleber Cisne Catão
#  Projeto: Desafio
#  Data de criação: 19/11/2025

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/desafio}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:amanha}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    flyway:
      locations: classpath:db/migration